### ISSUE TITLE
Cannot import on esp8266

### ISSUE THREAD

**Issue by ARF1** [SpotlightKid/micropython-ftplib#1]
Thanks for making this port of ftplib available. I am having issues importing it on esp8266 though.

If I import the esp8266 port compiled to `mpy`, I get the error:
```
>>> import ftplib                                                               
Traceback (most recent call last):                                              
  File "<stdin>", line 1, in <module>                                           
ValueError: incompatible .mpy file
```
If I import the esp8266 port as a `py` file, I get the error:
```
>>> import ftplib                                                               
Traceback (most recent call last):                                              
  File "<stdin>", line 1, in <module>                                           
MemoryError: memory allocation failed, allocating %u bytes 
```
Is there any simple fix you can think of?

**Comment by SpotlightKid** [comment]
If you are able to compile micropython yourself, you can try to compile the ftplib.py file to an .mpy file with a current version of mpy-cross.

**Comment by ARF1** [comment]
Thanks. mpy-cross did fix the problem on esp8266.
